# Generated by Django 3.0.8 on 2020-08-12 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyword_select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=100)),
                ('user_key', models.IntegerField()),
                ('author_id', models.CharField(max_length=100)),
                ('pos_text', models.TextField(null=True)),
                ('neg_text', models.TextField(null=True)),
                ('pos_text_norm', models.TextField(null=True)),
                ('neg_text_norm', models.TextField(null=True)),
                ('pos_keyword', models.TextField(null=True)),
                ('neg_keyword', models.TextField(null=True)),
                ('pos_word_num', models.TextField(null=True)),
                ('neg_word_num', models.TextField(null=True)),
                ('rand_order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=100)),
                ('key_index', models.IntegerField()),
                ('text', models.TextField()),
                ('words', models.TextField()),
                ('words_selected', models.TextField()),
                ('keywords', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tokenoutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='v1_Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(max_length=100)),
                ('session_index', models.IntegerField()),
                ('text', models.TextField()),
                ('words', models.TextField()),
                ('words_selected', models.TextField()),
                ('keywords', models.TextField(null=True)),
            ],
        ),
    ]
