# Generated by Django 3.0.8 on 2020-08-14 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_pk', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('pos_text', models.TextField(null=True)),
                ('neg_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_pk', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=100)),
                ('user_key', models.IntegerField()),
                ('author_id', models.CharField(max_length=100)),
                ('pos_text', models.TextField(null=True)),
                ('neg_text', models.TextField(null=True)),
                ('pos_text_norm', models.TextField(null=True)),
                ('neg_text_norm', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.DeleteModel(
            name='v1_Keywords',
        ),
        migrations.AddField(
            model_name='keyword_select',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='keyword_select',
            name='neg_text_norm_edited',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='keyword_select',
            name='pos_text_norm_edited',
            field=models.TextField(null=True),
        ),
    ]
