# Generated by Django 3.0.8 on 2020-08-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0003_progress_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='progress_state',
        ),
        migrations.CreateModel(
            name='progress_state',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latest_update', models.DateTimeField(blank=True, null=True)),
                ('cnt', models.IntegerField(null=True, verbose_name='total')),
                ('max_rand_order', models.IntegerField(null=True, verbose_name='completed')),
                ('progress', models.CharField(max_length=100)),
            ],
        ),
    ]
