# Generated by Django 3.0.8 on 2020-08-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0004_auto_20200819_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='agree_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='agree_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='agree_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='con_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='con_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='con_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='extra_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='extra_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='extra_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo1_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo2_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo3_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo4_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neg_emo5_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neuro_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neuro_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neuro_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='op_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='op_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='op_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo1_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo2_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo3_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo4_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pos_emo5_w',
            field=models.IntegerField(null=True),
        ),
    ]
