# Generated by Django 3.0.8 on 2020-11-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0005_auto_20200826_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyword_visualizer',
            fields=[
            ],
            options={
                'verbose_name': 'keyword visualizer',
                'verbose_name_plural': 'keyword visualizer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tokenizer.keyword_select',),
        ),
        migrations.AlterModelOptions(
            name='keyword_select',
            options={'verbose_name': 'keyword selection', 'verbose_name_plural': 'keyword selections'},
        ),
        migrations.AlterModelOptions(
            name='progress_state',
            options={'verbose_name': 'progress state', 'verbose_name_plural': 'progress states'},
        ),
        migrations.AddField(
            model_name='user_data',
            name='agree_avg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='con_avg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='extra_1R',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='extra_avg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='neuro_avg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='op_avg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='neg_emo1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='neg_emo2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='neg_emo3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='neg_emo4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='neg_emo5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pos_emo1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pos_emo2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pos_emo3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pos_emo4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pos_emo5',
            field=models.CharField(max_length=100),
        ),
    ]
