# Generated by Django 3.0.8 on 2020-11-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0007_auto_20201120_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='extra_1R',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
